[package]
name = "attribute_set"
version = "0.1.0"
authors = ["zhu.qing <zhu.qing@yitu-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
